export const LOAD_DATA = 'GET_DATA_REQUESTED';
export const GET_DATA = 'GET_DATA_SUCCESS';
export const FAILED_DATA = 'GET_DATA_FAILED';

export const LOAD_AREACHART_DATA = 'LOAD_AREACHART_DATA';
export const GET_AREACHART_DATA = 'GET_AREACHART_DATA_SUCCESS';
export const FAILED_AREACHART_DATA = 'GET_AREACHART_DATA_FAILED';